[project]
name = "ComfyUI-Image_Properties_SG"
description = "View general image properties of image: Dimension, Resolution, Aspect Ratio, Tensor Size (including batch)"
version = "1.0.1"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]


[project.urls]
Repository = "https://github.com/ShammiG/ComfyUI-Image_Properties_SG"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/ShammiG/ComfyUI-Image_Properties_SG/blob/main/README.md"
"Bug Tracker" = "https://github.com/ShammiG/ComfyUI-Image_Properties_SG/issues"

[tool.comfy]
PublisherId = "shammi-g"
DisplayName = "ComfyUI-Image_Properties_SG"
Icon = ""
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility



